title: "NUSpam"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md
  - Search.html

markdown: kramdown

repository: "AY2122S1-CS2103T-W13-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

tipue_search:
  include:
    pages: true
