title: "BogoBogo"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide - AB3.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S1-CS2103-F10-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
